### ISSUE TITLE
SyntaxError: Unexpected token: name (Renderer)

### ISSUE THREAD

**Issue by jesperwestlund1** [Dogstudio/highway#2] opened 2018-05-16 13:45 UTC
Hi! I'm trying to `import Highway from '@dogstudio/highway'` but I get this message...

```
[15:36:09] { GulpUglifyError: unable to minify JavaScript
    at createError (/Users/me/Sites/kendo/wp-content/themes/kendo-theme/node_modules/gulp-uglify/lib/create-error.js:6:14)
    at apply (/Users/me/Sites/kendo/wp-content/themes/kendo-theme/node_modules/lodash/_apply.js:16:25)
    at wrapper (/Users/me/Sites/kendo/wp-content/themes/kendo-theme/node_modules/lodash/_createCurry.js:41:12)
    at /Users/me/Sites/kendo/wp-content/themes/kendo-theme/node_modules/gulp-uglify/lib/minify.js:54:15
    at DestroyableTransform._transform (/Users/me/Sites/kendo/wp-content/themes/kendo-theme/node_modules/gulp-uglify/composer.js:10:23)
    at DestroyableTransform.Transform._read (/Users/me/Sites/kendo/wp-content/themes/kendo-theme/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/me/Sites/kendo/wp-content/themes/kendo-theme/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/Users/me/Sites/kendo/wp-content/themes/kendo-theme/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/Users/me/Sites/kendo/wp-content/themes/kendo-theme/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (/Users/me/Sites/kendo/wp-content/themes/kendo-theme/node_modules/readable-stream/lib/_stream_writable.js:334:11)
  cause: 
   { SyntaxError: Unexpected token: name (Renderer)
    at JS_Parse_Error.get (eval at <anonymous> (/Users/me/Sites/kendo/wp-content/themes/kendo-theme/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:21:1), <anonymous>:73:23)
    at formatError (util.js:620:16)
    at formatValue (util.js:526:18)
    at formatProperty (util.js:811:11)
    at formatObject (util.js:627:17)
    at formatValue (util.js:589:18)
    at inspect (util.js:302:10)
    at format (util.js:165:12)
    at Console.log (console.js:140:21)
    at log (/Users/me/Sites/kendo/wp-content/themes/kendo-theme/node_modules/fancy-log/index.js:36:15)
     message: 'Unexpected token: name (Renderer)',
     filename: 'app.js',
     line: 192,
     col: 6,
     pos: 6138 },
  plugin: 'gulp-uglify',
  fileName: '/Users/me/Sites/kendo/wp-content/themes/kendo-theme/build/app.js',
  showStack: false }
```

How to fix?

**Comment by Anthodpnt** [comment] 2018-05-16 15:09
Hi @jesperwestlund1,

Can you share your complete code so I can have a look and spot the issue ?
I might need to see the code where you use Highway and the Gulp task throwing the error as well.

Thanks,
Anthodpnt

**Comment by jesperwestlund1** [comment] 2018-05-17 06:16
Hi @Anthodpnt , yes of cource.

This in my app.js

```
import Highway from '@dogstudio/highway'

console.log('hello');
```

My javascript gulp.

```
'use strict';

var gulp = require('gulp');
var watchify = require('watchify');
var browserify = require('browserify');
var babelify = require('babelify');
var changed = require('gulp-changed');
var uglify = require('gulp-uglify');
var rename = require('gulp-rename');
var gutil = require('gulp-util');
var assign = require('lodash.assign');
var source = require('vinyl-source-stream');
var buffer = require('vinyl-buffer');

var customOpts = {
    entries: ['assets/js/main.js'],
    debug: true
};

var opts = assign({}, watchify.args, customOpts);
var bundler = watchify(browserify(opts).transform(babelify, {presets: ["es2015"]}));
var destination = './build';

gulp.task('js', bundle);
bundler.on('update', bundle);
bundler.on('log', gutil.log);

function bundle() {
  return bundler.bundle()
    .on('error', gutil.log.bind(gutil, 'Browserify Error'))
    .pipe(source('app'))
    .pipe(changed(destination))
    .pipe(rename({ extname: '.js' }))
    .pipe(gulp.dest(destination))
    .pipe(buffer())
    .pipe(uglify().on('error', gutil.log))
    .pipe(rename({ extname: '.min.js' }))
    .pipe(gulp.dest(destination))
}
```

**Comment by ThaoD5** [comment] 2018-05-17 07:26
Hello @jesperwestlund1, 
In order to test faster & have the most similar environment / configuration, could you zip your test & drop it here ? This way we can try to reproduce & solve your issue in the best conditions :-)

**Comment by jesperwestlund1** [comment] 2018-05-17 08:47
Hi @ThaoD5 , Yes here you have!

[kendo-theme.zip](https://github.com/Dogstudio/highway/files/2012372/kendo-theme.zip)

**Comment by Anthodpnt** [comment] 2018-05-17 09:27
@jesperwestlund1, I think the issue comes from the configuration of babelify in your package.json.

For now only the files coming from `assets/js` are compiled by babel using presets-2015. This means that Highway is never compiled since it comes from the node_modules and it need to pass through babel as explained in the documentation if you want to support all browsers.

I guess you can easily fix this issue by changing the `only` parameter of babelify with a regex including highway like `/(assets\/js|node_modules\/@dogstudio\/highway\/dist)/` or something.

Let me know if the issue came from this configuration :).

Best regards,
Anthony

**Comment by jesperwestlund1** [comment] 2018-05-17 10:12
@Anthodpnt Hmm... okey, I tried to import it manually like you say, I put **highway.js** in `assets/js/lib` then I import it like this in **main.js** 

`import highway from './lib/highway'` / `import './lib/highway'` / `import Highway from './lib/highway'`

and this is how it's look in my package.json

```
  "browser": {
    "config": "./assets/js/config.js",
    "highway": "./assets/js/lib/highway.js",
    "gsap-splitext": "./assets/js/lib/gsap/src/uncompressed/utils/SplitText.js",
    "gsap-scrollto": "./assets/js/lib/gsap/src/uncompressed/plugins/ScrollToPlugin.js"
  },
```

But it's not working.. the gulp file will not be completed.. when I run **gulp** in my console.

**Comment by Anthodpnt** [comment] 2018-05-17 14:10
@jesperwestlund1 Do you use babelify on Highway ?

**Comment by jesperwestlund1** [comment] 2018-05-17 14:12
@Anthodpnt babelify

**Comment by Anthodpnt** [comment] 2018-05-18 00:04
@jesperwestlund1,

The problem is that Babelify skips all `node_modules` folders but since Highway is part of the `node_modules` folders it's never transpiled into ES5 by Babelify.

Based on this [explanation](https://github.com/babel/babelify#why-arent-files-in-node_modules-being-transformed) you have to change a bit your `javascript.js` file with this:

```javascript
// YOUR CODE

var bundler = browserify(opts).transform(babelify, {
    global: true,
    ignore: /\/node_modules\/(?!@dogstudio\/highway\/)/,
    presets: ["env"]
});

// YOUR CODE
```

This will ignore all `node_modules` folders except for `node_modules/@dogstudio/highway`. So now Highway should be properly transpiled into ES5. This will solve the initial issue about `Renderer` apparently.

When testing I came across other errors I managed to fix by installing `babel-preset-env` instead of `babel-preset-es2015`. Check the Babel [documentation](https://babeljs.io/docs/plugins/preset-env/) about this preset.

Finally, there is one last thing to do that I couldn't manage to fix with your stack. You need to import `babel-polyfill` in you `main.js` file. But for a reason I ignore this always throw an `Unexpected end of input` error in the browser console... Check the Babel [documentation](https://babeljs.io/docs/usage/polyfill/#usage-in-node--browserify--webpack) about this polyfill.

Unfortunately I'm not used to work with Browserify and Babelify so you'll have to find a way to import `babel-polyfill` properly at the top of the `main.js` and fix the `Unexpected end of input` error by yourself.

I hope that it will help you and don't hesitate to keep me in touch.

Best regards,
Anthodpnt

**Comment by Anthodpnt** [comment] 2018-05-18 00:17
@jesperwestlund1 

An easier solution to properly transpile Highway to ES5 using Babelify is to: 

1. Put Highway in your `assets/lib` folder
2. Add `"highway": "./assets/js/lib/highway/highway.js",` in the `package.json` like earlier
3. Install `babel-preset-env` (check the [documentation](https://babeljs.io/docs/plugins/preset-env/))
4. Update your `javascript.js` file with this:

```javascript
// YOUR CODE

var bundler = browserify(opts).transform(babelify, { presets: ["env"] });

// YOUR CODE
``` 

This should also fix the initial `Renderer` issue from this thread.
But again you'll still have to add `babel-polyfill` and fix the error explained in previous comment.

Best regards,
Anthodpnt

**Comment by jesperwestlund1** [comment] 2018-05-18 11:02
@Anthodpnt Yes! thanks! that did the work! 👍

**Comment by Anthodpnt** [comment] 2018-05-18 11:15
@jesperwestlund1 Perfect, I close the issue then!

**Closed by Anthodpnt** 2018-05-18 11:15 UTC
